# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openocean_client
from openocean_client.models.listings_response import ListingsResponse  # noqa: E501
from openocean_client.rest import ApiException


class TestListingsResponse(unittest.TestCase):
    """ListingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListingsResponse(self):
        """Test ListingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openocean_client.models.listings_response.ListingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
