# coding: utf-8

"""
    OpenOcean-Api

    OpenOcean Swagger API Spec  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openocean_client
from openocean_client.models.offers import Offers  # noqa: E501
from openocean_client.rest import ApiException


class TestOffers(unittest.TestCase):
    """Offers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOffers(self):
        """Test Offers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openocean_client.models.offers.Offers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
